### ISSUE TITLE
Tracing subscriber refactor

### ISSUE THREAD

**Issue by david-crabnebula** [crabnebula-dev/devtools#16]
## Todo:

- [ ] Implement a method to easily load the subscriber, returning the associated layer, similar to how the [fmt](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/index.html) subscriber work.
- [ ] Simplify `on_events`
- [ ] Add span tracing functionality that includes:
    - `on_enter`: Track when a span is entered.
    - `on_close`: Track when a span is closed.
    - Time measurements for both busy and idle durations.
    - Metadata capture about the function call and parameters (specific details to be confirmed).
