### ISSUE TITLE
Implement an Aggregator

### ISSUE THREAD

**Issue by david-crabnebula** [crabnebula-dev/devtools#17]
## Todo:

- [ ] Establish an aggregator where data is directed to a dedicated channel. Data should be pre-filtered from the subscriber. No raw data should be sent.
- [ ] Channel data should then be directed to the WebSocket.
- [ ] Implement a mechanism to aggregate events approximately every Xms.
- [ ] Decide on a data structure for WebSocket submissions. Evaluate the simplicity of sending arrays of events instead of single events.

_Note: The overarching goal is to ensure WebSocket clients receive near-real-time updates, at user-defined intervals._

_Note 2: `tokio-console` Have a nice [`Aggregator`](https://github.com/tokio-rs/console/blob/main/console-subscriber/src/aggregator/mod.rs) that we should take inspiration and simplify by giving them the right credits, of course. (from @CrabNejonas)_
