### ISSUE TITLE
Simplify the plugin initialization

### ISSUE THREAD

**Issue by david-crabnebula** [crabnebula-dev/devtools#18]
Simplify and standardize the initialization of the plugin and inspector protocol in alignment with the tracing subscriber's behavior.

## Todo:

- [ ] Modify the initialization method to return the `layer` instead of the subscriber.
    ```rust
    let layer = inspector_protocol::layer()
        .with_max_level(LevelFilter::TRACE);
    ```
- [ ] Allow both `init` and `try_init` methods for initializing the layer.
- [ ] Ensure that the returned `layer` can be combined with other layers (Layered). This provides flexibility for developers to use the `fmt` subscriber simultaneously or any other layers as desired.
- [ ] Modify the Tauri builder integration to support the newly returned `layer`.  We could also leverage `.into()`

Example:
    ```rust
    .plugin(layer.plugin())
    ```
