### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by david-crabnebula** [crabnebula-dev/devtools#19]
Transition to [Polyform Shield](https://polyformproject.org/licenses/shield/1.0.0/). This change is the result of recent discussions and will be subject to future modifications, specifically concerning the subscriber and the whole plugin in the long run (after stabilization).

## Todo
- [ ] Create the `LICENSE` file
- [ ] Update license in `Cargo.toml` (SPDX)
- [ ] Licensing conflict check
